# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

builds:
  - skip: true

dockers_v2:
  - id: lxcfs-agent
    images:
    - ghcr.io/cndoit18/lxcfs-agent
    tags:
    - "{{ .Tag }}"
    - latest
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      GOLDFLAGS: -X 'github.com/cndoit18/lxcfs-on-kubernetes/version.AppVersion={{ .Version }}' -X 'github.com/cndoit18/lxcfs-on-kubernetes/version.GitCommit={{ .FullCommit }}'

    dockerfile: Dockerfile.agent
    extra_files:
      - scripts/
      
  - id: lxcfs-manager
    images:
    - ghcr.io/cndoit18/lxcfs-manager
    tags:
    - "{{ .Tag }}"
    - latest
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      GOLDFLAGS: -X 'github.com/cndoit18/lxcfs-on-kubernetes/version.AppVersion={{ .Version }}' -X 'github.com/cndoit18/lxcfs-on-kubernetes/version.GitCommit={{ .FullCommit }}'

    dockerfile: Dockerfile
    extra_files:
      - cmd/
      - pkg/
      - version/
      - go.mod
      - go.sum
      - scripts/

changelog:
  sort: asc

  filters:
    exclude:
      - "^docs:"
      - typo
      - (?i)foo

signs:
  - artifacts: checksum

release:
  draft: false
  prerelease: auto

  extra_files:
    - glob: charts/*.tgz
