# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - skip: true

dockers:
  - image_templates:
      - "ghcr.io/cndoit18/lxcfs-agent:{{ .Tag }}"
      - "ghcr.io/cndoit18/lxcfs-agent:latest"

    use: buildx

    build_flag_templates:
      - --platform=linux/amd64,linux/arm64
      - --push

    # buildx multi-arch outputs are manifest lists; they must be pushed to a registry
    # (cannot be exported/loaded into the local docker daemon).
    skip_push: true

    dockerfile: Dockerfile.agent
    extra_files:
      - scripts/

  - image_templates:
      - "ghcr.io/cndoit18/lxcfs-manager:{{ .Tag }}"
      - "ghcr.io/cndoit18/lxcfs-manager:latest"

    use: buildx

    build_flag_templates:
      - --platform=linux/amd64,linux/arm64
      - --push
      - --build-arg=GOLDFLAGS=-X 'github.com/cndoit18/lxcfs-on-kubernetes/version.AppVersion={{ .Version }}' -X 'github.com/cndoit18/lxcfs-on-kubernetes/version.GitCommit={{ .FullCommit }}'

    # buildx multi-arch outputs are manifest lists; they must be pushed to a registry
    # (cannot be exported/loaded into the local docker daemon).
    skip_push: true

    dockerfile: Dockerfile

    extra_files:
      - cmd/
      - pkg/
      - version/
      - go.mod
      - go.sum
      - scripts/

changelog:
  sort: asc

  filters:
    exclude:
      - "^docs:"
      - typo
      - (?i)foo

signs:
  - artifacts: checksum

release:
  draft: false
  prerelease: auto

  extra_files:
    - glob: charts/*.tgz
