# Copyright Yinan Li <cndoit18@outlook.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM ubuntu:22.04 as builder

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y python3 python3-jinja2 python3-setuptools meson wget gcc cmake libfuse2 libfuse-dev uuid-runtime systemd help2man pkg-config

ENV LXCFS 6.0.4
RUN wget https://linuxcontainers.org/downloads/lxcfs/lxcfs-$LXCFS.tar.gz && \
	mkdir /lxcfs && tar xzvf lxcfs-$LXCFS.tar.gz -C /lxcfs && \
	cd /lxcfs/lxcfs-$LXCFS && \
	meson setup -Dinit-script=systemd --prefix=/usr build/ && \
	meson compile -C build/ && \
	meson install -C build/

RUN ls -l /usr/lib/x86_64-linux-gnu/lxcfs/
RUN ls -l /usr/bin/lxcfs && \
	ls -l /usr/lib64/ && \
	ls -l /lib/x86_64-linux-gnu/libdl.so* && \
	ls -l /lib/x86_64-linux-gnu/libfuse.so* && \
	ls -l /lib/x86_64-linux-gnu/libgcc_s.so* && \
	ls -l /lib/x86_64-linux-gnu/libpthread.so* && \
	ls -l /lib/x86_64-linux-gnu/libc.so* && \
	ls -l /lib64/ld-linux-x86-64.so*

FROM gcr.io/distroless/base@sha256:d8244d4756b5dc43f2c198bf4e37e6f8a017f13fdd7f6f64ec7ac7228d3b191e

COPY --from=builder /usr/bin/lxcfs /usr/bin/lxcfs
COPY --from=builder /usr/lib64/lxcfs /usr/lib64/lxcfs
COPY --from=builder /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so.2
COPY --from=builder /lib/x86_64-linux-gnu/libfuse.so.2 /lib/x86_64-linux-gnu/libfuse.so.2
COPY --from=builder /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libgcc_s.so.1
COPY --from=builder /lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libpthread.so.0
COPY --from=builder /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY --from=builder /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2

ENTRYPOINT [ "lxcfs" ]