# Copyright Yinan Li <cndoit18@outlook.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM buildpack-deps:noble AS builder

SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update; \
	apt-get install -y --no-install-recommends meson python3-jinja2 libfuse3-dev help2man systemd

WORKDIR /lxcfs
ARG LXCFS=6.0.4
RUN wget -q "https://linuxcontainers.org/downloads/lxcfs/lxcfs-$LXCFS.tar.gz" -O - | \
	tar -xzf - --strip-components=1
RUN meson setup -Dinit-script=systemd --prefix=/usr build/; \
	meson compile -C build/; \
	meson install -C build/

WORKDIR /opt/tools 
ARG CRICTLVERSION="1.33.0"
RUN wget -q "https://github.com/kubernetes-sigs/cri-tools/releases/download/v$CRICTLVERSION/crictl-v$CRICTLVERSION-linux-amd64.tar.gz" && tar -xzf "crictl-v$CRICTLVERSION-linux-amd64.tar.gz"

WORKDIR /rootfs
RUN ARCH="$(uname -m)"; \
	mkdir -p "usr/bin" "usr/lib/$ARCH-linux-gnu/lxcfs" "lib/$ARCH-linux-gnu" "lib64"; \
	cp "/usr/bin/lxcfs" "usr/bin/"; \
	cp "/usr/lib/$ARCH-linux-gnu/lxcfs/liblxcfs.so" "usr/lib/$ARCH-linux-gnu/lxcfs/"; \
	cp "/lib/$ARCH-linux-gnu/libdl.so.2" "lib/$ARCH-linux-gnu/"; \
	cp "/lib/$ARCH-linux-gnu/libfuse3.so.3" "lib/$ARCH-linux-gnu/"; \
	cp "/lib/$ARCH-linux-gnu/libgcc_s.so.1" "lib/$ARCH-linux-gnu/"; \
	cp "/lib/$ARCH-linux-gnu/libpthread.so.0" "lib/$ARCH-linux-gnu/"; \
	cp "/lib/$ARCH-linux-gnu/libc.so.6" "lib/$ARCH-linux-gnu/"; \
	cp "/lib/$ARCH-linux-gnu/ld-linux-${ARCH//_/-}.so."* "lib64/"

# alpine:3.22.0
FROM alpine@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715 

COPY --from=builder /rootfs/ /
COPY --from=builder /opt/tools/crictl /usr/local/bin/crictl
COPY scripts/lxcfs-remount.sh /usr/local/bin/lxcfs-remount.sh

ENTRYPOINT [ "lxcfs" ]