apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager-daemonset
  namespace: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: lxcfs-agen
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: agent
          args:
            - "/var/lib/lxcfs-on-k8s/lxcfs"
          volumeMounts:
            - name: lxcfs
              mountPath: /var/lib/lxcfs-on-k8s/lxcfs
              mountPropagation: Bidirectional
      volumes:
        - name: lxcfs
          hostPath:
            path: /var/lib/lxcfs-on-k8s/lxcfs
            type: DirectoryOrCreate
