apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/component: lxcfs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: lxcfs
  template:
    metadata:
      labels:
        app.kubernetes.io/component: lxcfs
    spec:
      containers:
      - image: ghcr.io/cndoit18/lxcfs-manager:dev
        imagePullPolicy: Always
        args:
        - --lxcfs-path=/var/lib/lxcfs
        name: manager
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 500m
            memory: 300Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: system
  name: controller-manager-daemonset
  labels:
    app.kubernetes.io/component: lxcfs-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: lxcfs-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/component: lxcfs-agent
    spec:
      hostPID: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: agent
        image: ghcr.io/cndoit18/lxcfs-agent:dev
        imagePullPolicy: Always
        args:
          - "/var/lib/lxcfs"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: lxcfs
          mountPath: /var/lib/lxcfs
          mountPropagation: Bidirectional
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: lxcfs
        hostPath:
          path: /var/lib/lxcfs
          type: DirectoryOrCreate