apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/component: lxcfs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: lxcfs
  template:
    metadata:
      labels:
        app.kubernetes.io/component: lxcfs
    spec:
      containers:
      - image: ghcr.io/cndoit18/lxcfs-manager:dev
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 300m
            memory: 200Mi
        ports:
        - name: ready
          containerPort: 5000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: ready
        readinessProbe:
          httpGet:
            path: /readyz
            port: ready
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: system
  name: controller-manager-daemonset
  labels:
    app.kubernetes.io/component: lxcfs-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: lxcfs-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/component: lxcfs-agent
    spec:
      hostPID: true
      containers:
      - name: agent
        image: ghcr.io/cndoit18/lxcfs-agent:dev
        securityContext:
          privileged: true
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup