namePrefix: '{{ include "chart.fullname" . }}-'

namespace: '{{ .Release.Namespace | quote }}'

generatorOptions:
  disableNameSuffixHash: true

patches:
- patch_clusterrolebinding.yaml

bases:
- ../../rbac
