apiVersion: v1
kind: Service
metadata:
  name: '{{ include "chart.fullname" . }}-controller-manager'
  namespace: {{ .Release.Namespace | quote }}
  labels:
    labels: {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
