# replicas -- Number of replicas for the controller
replicas: 3

image:
  # image.manager -- lxcfs-on-kubernetes controller image
  manager: ghcr.io/cndoit18/lxcfs-manager:latest
  # image.agent -- lxcfs-on-kubernetes agent image
  agent: ghcr.io/cndoit18/lxcfs-agent:latest

# <https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#servicespec-v1-core>
service:
  # service.type -- Service type to use
  type: ClusterIP
  # service.port -- Expose port for WebHook controller
  port: 443

# logLevel -- Set the verbosity of controller. Range of 0 - 6 with 6 being the most verbose.
# Info level is 4.
logLevel: 4

leaderElection:
  # leaderElection.enable -- Whether to enabled leaderElection
  enable: false
  # leaderElection.namespace -- The namespace used to store the ConfigMap for leader election
  namespace: kube-system
  # leaderElection.id -- The id used to store the ConfigMap for leader election
  id: lxcfs-on-kubernetes-leader-election

# imagePullSecrets -- Reference to one or more secrets to be used when pulling images
# <https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/>
# For example:
# `[
#   {"name":"image-pull-secret"}
# ]`
imagePullSecrets: []

# pullPolicy -- The image pull policy.
pullPolicy: IfNotPresent

# resources -- Expects input structure as per specification <https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#resourcerequirements-v1-core>
resources:
  limits:
    cpu: 500m
    memory: 300Mi
  requests:
    cpu: 300m
    memory: 200Mi

# podAnnotations -- Additional annotations to add to the controller Pods
podAnnotations: {}

lxcfs:
  # lxcfs.mountPath -- Specify the mount path of lxcfs on the host
  mountPath: /var/lib/lxcfs
  # lxcfs.resources -- Expects input structure as per specification <https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#resourcerequirements-v1-core>
  resources:
    limits:
      cpu: 500m
      memory: 300Mi
    requests:
      cpu: 300m
      memory: 200M
  # lxcfs.matchLabels -- For namespaces that match the labes, the Pods under it will mount lxcfs.
  matchLabels: 
    mount-lxcfs: enabled
  # podAnnotations -- Additional annotations to add to the agent Pods
  podAnnotations: {}